# NumPy Data types 

In [87]:
import numpy as np

In [89]:
z = np.arange(3, dtype = 'uint8')   # unsigned integer
print(z)
print()
print(z.dtype)
z

[0 1 2]

uint8


array([0, 1, 2], dtype=uint8)

In [90]:
x = np.array([1,2,3], dtype = 'f')  # floating-point number
x.dtype

dtype('float32')

In [91]:
y = np.array([4,5,6], dtype = 'float32')  # floating-point number
y.dtype

dtype('float32')

In [92]:
k = np.array([7,8,9], dtype = 'd')  # double-precision floating-point number
k.dtype

dtype('float64')

In [95]:
m = np.array([-10, 20, 30])
m.dtype

dtype('int64')

In [98]:
p = np.array([10, 20, 30], dtype = 'int')
p.dtype

dtype('int64')

In [101]:
n = np.array([-10.1, 20, 30], dtype = 'int')
n, n.dtype

(array([-10,  20,  30]), dtype('int64'))

In [103]:
dt = np.dtype(float)   # Python-compatible floating-point number
print(dt)
dt = np.dtype(int)     # Python-compatible integer
print(dt)
dt = np.dtype(object)  # Python object
print(dt)

float64
int64
object


# Iterating over arrays

In [104]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [105]:
for x in a:
    print(x, end=' ')

[0 1 2] [3 4 5] 

In [108]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):                       #default order = 'K'  keep the existing order
    print(x, end= ' ')

0 1 2 3 4 5 

In [125]:
a = np.arange(8).reshape(4,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [128]:
for x in np.nditer(a):               #default order = 'K'  keep the existing order
    print(x, end = ' ')

0 1 2 3 4 5 6 7 

In [127]:
for x in np.nditer(a, order='K'):    #order = 'K'  keep the existing order
    print(x, end = ' ')

0 1 2 3 4 5 6 7 

In [126]:
for x in np.nditer(a, order='C'):    #order = 'C'  force C-order iteration
    print(x, end = ' ')

0 1 2 3 4 5 6 7 

In [129]:
a = np.arange(8).reshape(4,2)        #order = 'F'  force Fortran-order iteration
for x in np.nditer(a, order='F'):
    print(x, end = ' ')

0 2 4 6 1 3 5 7 

In [119]:
a = np.arange(8).reshape(4,2)
for x in np.nditer(a):
    print(x, end= ' ')

0 1 2 3 4 5 6 7 

In [120]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [118]:
a.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [121]:
a = np.arange(8).reshape(4,2)
for x in np.nditer(a.T):
    print(x, end= ' ')

0 1 2 3 4 5 6 7 

In [130]:
a = np.arange(8).reshape(4,2)
for x in np.nditer(a.T, order='C'):
    print(x, end= ' ')

0 2 4 6 1 3 5 7 

## a.T is a view, not a copy

## underlying memory order stays the same

## np.nditer iterates in memory-efficient order, not logical index order

In [134]:
a = np.arange(8).reshape(4,2)
for x in np.nditer(a.T, order='F'):
    print(x, end= ' ')
print()
for x in np.nditer(a.T, order='C'):
    print(x, end= ' ')

0 1 2 3 4 5 6 7 
0 2 4 6 1 3 5 7 

# one-two dimensional NumPy arrays, vectorization, broadcasting, and universal function

In [2]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]

In [4]:
print([[i+1 for i in row] for row in matrix])

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]


In [5]:
# This is looping through each element and it is slow for large arrays

In [10]:
# construct an array with a simple list resulting in a 1d array

arr1 = np.array([10,100,1000])
print(arr1)

# construct an array with a nested list resulting in a 2d array

arr2 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr2)

[  10  100 1000]
[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [12]:
print(arr1[0], float(arr1[0]))

10 10.0


In [15]:
arr3 = np.array([10,100,1000.])
print(arr3)
print(arr3.dtype)

[  10.  100. 1000.]
float64


In [17]:
print(arr3+1)

[  11.  101. 1001.]


# Vectorization

In [21]:
# If you sum of a scaler and a NumPy array, NumPy will perform an element-wise operation, 
# and you don't have to loop through the elements
# This element-wise operation is "Vectorization", code remains concise and operations are much faster

In [22]:
print(arr3+1)

[  11.  101. 1001.]


# Broadcasting 

In [25]:
# When you are working on two arrays, NumPy performs operation element-wise
# If the two arrays are with different shapes, NumPy extends the smaller array automatically 
# across the larger array so that their shapes are compatible. 
# This is "broadcasting"
arr2 * arr2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

# Matrix multiplication OR dot product done using @ operator

In [27]:
arr2.T # Transpose

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [29]:
arr2.shape, arr2.T.shape

((2, 3), (3, 2))

In [32]:
arr2 @ arr2.T  # matrix multiplication or dot product using @ operator

array([[14., 32.],
       [32., 77.]])

In [33]:
import math

print(math.sqrt(arr2))

In [35]:
print(math.sqrt(arr1))

TypeError: only length-1 arrays can be converted to Python scalars

In [36]:
arr1.shape

(3,)

In [37]:
arr0 = np.array([1000])
print(arr0)
print(arr0.shape)
print(math.sqrt(arr0))

[1000]
(1,)
31.622776601683793


C:\Users\navee\AppData\Local\Temp\ipykernel_25628\2483035372.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(math.sqrt(arr0))


In [39]:
[math.sqrt(i) for i in arr1]

[3.1622776601683795, 10.0, 31.622776601683793]

In [41]:
[[math.sqrt(i) for i in row] for row in arr2]

[[1.0, 1.4142135623730951, 1.7320508075688772],
 [2.0, 2.23606797749979, 2.449489742783178]]

# universal functions (ufunc)  np.sqrt, np.sum

In [44]:
print(np.sqrt(arr1))

[ 3.16227766 10.         31.6227766 ]


In [45]:
np.sum(arr1)

np.int64(1110)

In [46]:
np.sum(arr2)

np.float64(21.0)

# the universal functions (ufunc) are available as array methods also 
## array.sum(axis=0), array.sum(axis=1)

In [49]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr2.sum(axis=0)  # returns a 1d array

array([5., 7., 9.])

In [51]:
arr2.sum(axis=1)

array([ 6., 15.])

In [54]:
print(arr1)
print()
print(arr2)

[  10  100 1000]

[[1. 2. 3.]
 [4. 5. 6.]]


In [55]:
arr2[1,:]

array([4., 5., 6.])

In [56]:
arr2[:, 2] # returns a 1d array

array([3., 6.])

In [57]:
arr2[:, 1:].shape  # returns a 2d array

(2, 2)

In [58]:
arr2[:, 1:]

array([[2., 3.],
       [5., 6.]])

In [59]:
arr2[1,1]  # returns a scalar

np.float64(5.0)

# array constructors  

## np.arange(10).reshape(2,5)  np.random.randn(2,3)

In [63]:
np.arange(2*5).reshape(2,5)  # 2 rows 5 cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
np.arange(3*4).reshape(3,4)  # 3 rows 4 cols

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.random.randn(2,4) # 2 rows 4 cols

array([[ 0.98043106, -0.5199222 , -0.28433368,  0.28523254],
       [-1.17289639,  0.13904777, -1.20963754, -0.72267286]])

# View  vs  Copy

In [66]:
array2 = np.arange(2*5).reshape(2,5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
subset = array2[:,2:]   # slicing returns a view not a copy
subset

array([[  2,   3,   4],
       [  7,   8, 100]])

In [73]:
subset[1,2] = 100   # modifying the view will also modify the original array
subset

array([[  2,   3,   4],
       [  7,   8, 100]])

In [74]:
array2

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8, 100]])

In [78]:
array2 = np.arange(2*5).reshape(2,5)
print(array2)
print()
subset = array2[:, 2:].copy()  # Now slicing actually creates a copy
subset[1,2] = 100
print(subset) 
print()
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[  2   3   4]
 [  7   8 100]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [136]:
print(arr1)
print()
print(arr2)

[  10  100 1000]

[[1. 2. 3.]
 [4. 5. 6.]]


In [137]:
arr2.sum(axis=0)

array([5., 7., 9.])

In [138]:
arr2.sum(axis=1)

array([ 6., 15.])

# Conclusion

## NumPy Arrays

A **NumPy array** is an **N-dimensional array designed for homogeneous data**.  
This means every element in the array must have the **same data type**.

Example:

```python
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)
```

---

## NumPy Data Types (dtypes)

NumPy arrays store elements with a specific **data type (`dtype`)**.

Common types include:

- `int`
- `float`
- `object` (used for strings or mixed types)

Example:

```python
arr = np.array([1, 2, 3])
print(arr.dtype)
```

---

## Homogeneous Data

NumPy arrays hold **homogeneous data** (same data type).

You can check the data type using:

```python
arr.dtype
```

Example:

```python
arr = np.array([1, 2, 3])
print(arr.dtype)   # int64 (may vary by system)
```

---

## Vectorization (Element-wise Operations)

**Vectorization** allows NumPy to perform operations **element-wise across arrays** without writing explicit loops.

Example:

```python
arr = np.array([1, 2, 3])

result = arr * 2
print(result)
```

Output:

```
[2 4 6]
```

---

## Broadcasting

**Broadcasting** allows NumPy to perform operations on arrays of **different shapes** by automatically expanding the smaller array so the shapes are compatible.

Example:

```python
arr = np.array([1, 2, 3])

result = arr + 5
print(result)
```

Output:

```
[6 7 8]
```

NumPy automatically broadcasts the scalar `5` across the array.

---

## Matrix Multiplication (Dot Product)

Matrix multiplication in NumPy can be performed using the **`@` operator**.

Example:

```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = A @ B
print(C)
```

---

## Matrix Transposition

Transposing a matrix swaps its rows and columns.

Use the `.T` attribute:

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)
```

---

## Scalars vs 1D vs 2D Arrays

NumPy indexing can return **different types of results** depending on how you slice.

Example:

```python
arr = np.array([[1, 2],
                [3, 4]])
```

| Expression | Result |
|-------------|--------|
| `arr[1,1]` | Scalar |
| `arr[1, :]` | 1D array |
| `arr[:, 1]` | 1D array |

---

## Scalar

A **scalar** refers to a single basic Python value, such as:

- `int`
- `float`
- `string`

Example:

```python
value = arr[1,1]
print(type(value))
```

---

## 1D Arrays

A **1D array** has only **one axis**.

Example:

```python
arr1 = np.array([1, 2, 3, 4])
```

Operations along axes:

```python
arr1.sum(axis=0)   # valid
```

Using `axis=1` will produce an **out-of-bounds error** because a 1D array only has one axis.

---

## Key Takeaways

- NumPy arrays store **homogeneous data**
- The data type is accessed using **`array.dtype`**
- **Vectorization** enables fast element-wise operations
- **Broadcasting** allows operations on arrays with different shapes
- Matrix multiplication uses **`@`**
- Transpose uses **`.T`**
- Indexing determines whether you get a **scalar, 1D array, or 2D array**